-- Abuddy Cloud Database Schema for Supabase
-- Run this in your Supabase SQL Editor: https://app.supabase.com

-- 1. Create Stays Table
create table if not exists public.stays (
    id bigint primary key,
    title text not null,
    area text not null,
    type text not null,
    gender text default 'Any',
    rent numeric not null,
    deposit numeric,
    electricity text,
    "desc" text,
    amenities text[] default array[]::text[],
    image text,
    gallery text[] default array[]::text[],
    landlord text,
    rating numeric default 4.8,
    review_count integer default 1,
    verified boolean default true,
    available_from text default 'Available now',
    distance numeric default 1.5,
    rules text[] default array['No smoking indoors', 'Keep common areas clean']::text[],
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create Visit Requests Table
create table if not exists public.visit_requests (
    id bigint generated by default as identity primary key,
    stay_id bigint,
    stay_title text,
    student_name text not null,
    student_email text not null,
    date text not null,
    time text not null,
    status text default 'Pending',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable Row Level Security (RLS)
alter table public.stays enable row level security;
alter table public.visit_requests enable row level security;

-- 4. Create Public Policies (Allows viewing & booking during live classroom demo)
drop policy if exists "Allow public read on stays" on public.stays;
create policy "Allow public read on stays" on public.stays for select using (true);

drop policy if exists "Allow public insert on stays" on public.stays for insert with check (true);
create policy "Allow public insert on stays" on public.stays for insert with check (true);

drop policy if exists "Allow public update on stays" on public.stays for update using (true);
create policy "Allow public update on stays" on public.stays for update using (true);

drop policy if exists "Allow public read on visit_requests" on public.visit_requests;
create policy "Allow public read on visit_requests" on public.visit_requests for select using (true);

drop policy if exists "Allow public insert on visit_requests" on public.visit_requests;
create policy "Allow public insert on visit_requests" on public.visit_requests for insert with check (true);

drop policy if exists "Allow public update on visit_requests" on public.visit_requests;
create policy "Allow public update on visit_requests" on public.visit_requests for update using (true);

-- 5. Enable Realtime Replication
do $$
begin
  if not exists (
    select 1 from pg_publication_tables 
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'stays'
  ) then
    alter publication supabase_realtime add table public.stays;
  end if;
  if not exists (
    select 1 from pg_publication_tables 
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'visit_requests'
  ) then
    alter publication supabase_realtime add table public.visit_requests;
  end if;
end $$;
